spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: bamboo

  datasource:
    url: jdbc:mysql://dkost-s-sql-001.unwire.com:3306/ticketing_core_ci_test?autoReconnect=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: bamboo_flyway
    password: HtF9q52UgufA8wns

---
spring:
  profiles: default

  datasource:
    url: jdbc:mysql://localhost:3306/ticketing_core_ci_test?autoReconnect=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: mticket
    password: mticket

---
spring:
  profiles: server-local, server-test, server-staging, server-production

  datasource:
    jndi-name: java:jboss/ticketing_core

